//예외를 던지고 캐치하기
import java.util.Scanner;

class Main {

  static void check(int sw) throws Exception{
    switch (sw) {
      case 1: throw new Exception("검사 예외 발생!");
      case 2: throw new RuntimeException("비검사 예외 발생!");
    }
  }

  static void test(int sw) throws Exception{
    check(sw); 
  }

  public static void main(String[] args) {
    Scanner stdIn = new Scanner(System.in);

    System.out.print("sw:");
    int sw = stdIn.nextInt();

    try {
      test (sw);
    } catch (RuntimeException e) {
      System.out.println(e.getMessage());
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}
//check:  인수 sw 받은 값에 따라 Exception 또는 RuntimeException 예외를 던지는 메서드

//메서드 본체의 switch에서 sw값에 따라 예외를 던진다. 예외를 던지는 구문에 throw "throw식"  인스턴스를 new로 생성해서 던진다.

//test 메서드는 check 메서드를 호출하는게 전부인 메서드이다. 호출되는 check 메서드에서 Exception이 발생한다는 것을 프로그래머와 컴파일러는 알고있다. test메서드도 에러가 발생할 가능성도 있다. throws Exception이라는 throw 절 지정이 필수이다.

//Exception을 캐치하면 "검사 예외 발생!" RuntimeException을 캐치하면 "비검사 예외발생!" 출력

